### ISSUE TITLE
nouvelles données législatives

### ISSUE THREAD

**Issue by richarddelome** [pollsposition/data#57]
[Voilà un dataset](https://drive.google.com/file/d/1aDdbk_U8udQEzIGxPbwsPjALm0nkhId4/view) qui contient toutes les données des législatives depuis 1958 présentes sur [data gouv](https://www.data.gouv.fr/fr/pages/donnees-des-elections-et-referendums/), nettoyées et standardisées.

Avant 1993, ce sont les données de Sciences Po et celles du ministère après.

Les données sont par départements/circonscriptions/communes/bureaux de vote. En comparant ces différentes niveaux vous verrez qu'il y a parfois des différences dans les datasets, soit parce qu'il manque les données de l'outre-mer/français de l'étranger soit parce qu'il y a des erreurs, par exemple des départements ou des communes absentes. 

[Voilà la fonction](https://gist.github.com/richarddelome/4e6aac3ff473b3ebb2b774828a0608a6) que j'ai utilisée pour nettoyer les données du ministère. Marche aussi pour tous les autres types d'élections a priori.

En espérant que ça vous aide un peu!

**Comment by rlouf** [comment]
Incroyable, merci de ta contribution ! Closed by #58

**Comment by dlmrr** [comment]
De rien, c'était cool à faire quand même :-)

Mon adresse mail pour le commit : celle-ci même et le nom : richarddelome:
https://github.com/richarddelome

J'ai déjà fait toutes les autres élections, mêmes les cantonales et les
sénatoriales, mais il faut que je vérifie les résultats.
Et puis je me suis rendu compte hier qu'il y avait toutes les élections
depuis 2000 dans un format xml plus fiable et plus facile à prendre en main
donc je me demande si je ne vais pas tout refaire à partir de celui-ci.

Au plaisir!
Richard
